batch_size: 64
data_dir: gs://iris-us/tfds_datasets
dataset: imagenet2012
learning_rate: 0.0001
round: false
save: false
base_saving_path: gs://iris-us/jsm/research/code-length-estimator
suffix: ''
qf: '50,100'
